name: gemini_chat_flutter
description: "Sample app for the google_generative_ai package"

publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_markdown: any
  google_generative_ai: ^0.4.3
  envied: ^0.5.4+1
  student_app:
    path: ../student_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - ../student_app/sensitive.env
